### ISSUE TITLE
Support for renames

### ISSUE THREAD

**Issue by sharkykh** [letmaik/vscode-git-tree-compare#52]
Hi and thank you for this awesome extension!

Would it be possible to add support for renames? I see that you currently explicitly ignore renames (`git diff-index --no-renames :ref: --`).
Maybe you could put it behind a configuration option that defaults to disabled?

**Comment by letmaik** [comment]
Sounds useful. I think I disabled renames mostly to reduce complexity but also because this makes it slower. Do you want to give it a try yourself? Just clone the repo, do `npm install` and hit F5.

**Comment by sharkykh** [comment]
It doesn't work right now because the `R` status is not supported.
```
Ignoring updateDiff() error during initial getChildren() Error: unsupported git status: R
	at sanitizeStatus (c:\Dev\vscode-git-tree-compare\dist\extension.js:1738:15)
	at module.exports.diffIndexResult.stdout.trim.split.filter.map.line (c:\Dev\vscode-git-tree-compare\dist\extension.js:1765:43)
	at Array.map (<anonymous>)
	at Object.diffIndex (c:\Dev\vscode-git-tree-compare\dist\extension.js:1765:10)
```

**Comment by letmaik** [comment]
Sure, some changes are necessary. I probably won't have time to work on this myself currently, but if you can make it work and submit a PR, then I'm happy to review/test/merge it.
